socket.server:
  frontend:
    first:
      host: localhost
      port: 9000
    second:
      host: localhost
      port: 9001
  database:
    first:
      host: localhost
      port: 9010
    second:
      host: localhost
      port: 9011