socket.server:
  frontend:
    host: localhost
    ports: 9000
  database:
    host: localhost
    ports: 9010

web.server.frontend.ports: 8080

path.to.jar:
  database: hw30multiprocessing/hw30databaseclient/target/hw30-database-client-1.0.jar
  frontend: hw30multiprocessing/hw30frontendclient/target/hw30-frontend-client-1.0.jar
